spring:
  application:
    name: item-service
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: test
    password: test123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
#server:
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

---
spring:
  profiles: item1

server:
  port: 8001

---
spring:
  profiles: item2

server:
  port: 8002
